### PR TITLE
Create open games list

### PR DESCRIPTION
**Pull request by rjdellecese**
@lasley Is there anything I should test here? I didn't think so, but just want to be sure.

### CODE REVIEW

**Comment by lasley** [comment]
@rjdellecese General rule is to test any login. The logic here would be whether the open games are displayed.

**Comment by lasley** [comment]
@rjdellecese Did you want to add the tests described above, or did you just want me to review & merge?

**Comment by rjdellecese** [comment]
@lasley Sorry for not responding--I'd definitely like to write tests per your recommendation; I just didn't have time yesterday to. I'll write tests and update this evening.

**Comment by lasley** [comment]
@rjdellecese No worries, just wanted to make sure this wasn't waiting on me :smile: 

We've got some merge conflicts too while you're at it. Luckily we're about out of all the core development, so the merge conflicts will start to thin out

**Comment by rjdellecese** [comment]
@lasley Assuming those tests look good (let me know if you think there is anything else I should have tested for) I think this is ready to merge!

**Comment by lasley** [comment]
:+1:

**Pull request merged**
