### PR TITLE
Michael

### PR DESCRIPTION
**Pull request by Mikeysax**
Added simple form, devise, and static pages controller with index, games controller with crud and game model.

### CODE REVIEW

**Comment by lasley** [comment]
@Mikeysax - Looks like this branch is failing. We'll need to start with a working build

**Comment by Mikeysax** [comment]
@lasley I tried to add Travis but I think I've done something improperly? Trying to figure it out still. Any ideas?

**Comment by lasley** [comment]
What's wrong about it? I just see a build failure - https://travis-ci.org/Firechess/firechess

**Comment by lasley** [comment]
Hist: Travis is `test` environment, not `development`

**Comment by Mikeysax** [comment]
Travis says that it cannot find the .travis.yml. Still unsure of why? That's why it's erroring.

**Comment by lasley** [comment]
@Mikeysax - Can you link me to that error? This is the one I'm seeing - https://travis-ci.org/Firechess/firechess/builds/103184012#L175

**Comment by Mikeysax** [comment]
At the top of the run it says: Could not find .travis.yml, using standard configuration.

**Comment by Mikeysax** [comment]
@lasley There are a few errors but I'm trying to fix the first one which says it can't find my .travis.yml file. I put it in the root but it's not seeing it for whatever reason.

**Comment by lasley** [comment]
Looks like you're missing a critical component in your Travis YML. Take a look at - https://docs.travis-ci.com/user/languages/ruby and compare what you have vs. there's

**Comment by Mikeysax** [comment]
@lasley Was it the language? I ran the build again but it still cannot find .travis.yml.

**Comment by lasley** [comment]
@Mikeysax  - Yeah that's what I was thinking it was. Was this repo renamed or anything? Maybe try going into Travis & resync

**Comment by Mikeysax** [comment]
@lasley The repo wasn't renamed. Anthony started the Travis implementation so I don't know if he did anything weird but I readded the repo to travis. I tried resyncing and it still doesn't see the .travis.yml file. Very confused...

**Comment by lasley** [comment]
@Mikeysax - I don't see a build in the past 40 minutes

**Comment by lasley** [comment]
NVM refreshing would help

**Comment by lasley** [comment]
Following the commit in Travis, the file isn't actually there. https://github.com/Firechess/firechess/tree/e8cd348332ed8522e9364eae39c617198e3213d9

Seems like there is something wrong here. Try turning travis off for the repo, turn it back on, push again

Off and On Again

**Comment by Mikeysax** [comment]
I removed Travis CI and added codeship lol, talk about easy.

**Comment by lasley** [comment]
Works for me. Maybe squash these commits down to a few logical chunks in order to not saturate our timeline with testing - http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Let me know when you're ready for merge and I'll look at everything again.

**Comment by lasley** [comment]
Also, let's get Rubocop added to Codeship too - http://buildtoship.com/integrate-rubocop-in-your-workflow/

**Comment by Mikeysax** [comment]
Okay I rebased a few things, and rubocop was added to codebase when I set it up with slack notifications . Is that good?

**Comment by lasley** [comment]
:+1:

**Comment by Mikeysax** [comment]
:sunglasses: :metal:

**Pull request merged**
